export * from "./DetalleMateria"
export * from "./DetallePlanSemestre"
export { default as DetalleMateriaV2 } from "./DetalleMateriaV2"
export { default as MateriaHistoricoItem } from "./MateriaHistoricoItem"
export { default as MateriaChartsDetail } from "./MateriaChartsDetail"